### ISSUE TITLE
Make links cleaner

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#139]
Feedback from an almost random user:

I want cleaner links.
Something like `delegit.xyz/chaosdao-polkadot`

The solution to this would be to create our own mapping of:
- name => address + network

Any delegate willing to have a clean name will have to open an issue/PR which is totally fine. We can do it for the current set.

Here's the behavior:
- user comes to delegit.xyz/somename
- we look in our mapping, and redirect to delegit/delegate/[address]?network=[network]
- we give the nice link in a way or another, this is linked to https://github.com/delegit-xyz/dashboard/pull/137#issuecomment-2352384491

**Comment by wirednkod** [comment]
I do not think that this mapping is needed.
We have already the name of the delegate that we can sanitize and cleanup spaces, emojis etc etc... this way we have already a clean Link that we can provide to the delegate if needs to use it for sharing the page.
In case a delegate wants a specific name instead of the existing one, we can add maybe some exception, but I think keeping a mapping without anyone requesting it is much harder than just sanitizing the already given name that they have.

**Comment by Tbaut** [comment]
totally, if we end up with nice urls still, that's perfect.
