### ISSUE TITLE
Polkadot-SDK Facade Feedback

### ISSUE THREAD

**Issue by kianenigma** [delegit-xyz/dashboard#189]
We are working towards building better APIs to simplify the interacting with "Polkadot Network". 

What do we mean here by Polkadot Network? Foremost Polkadot Relay Chain and System Chains (everything DOT related), and then other Parachains. 

In a few months (and after gathering feedback via such issues), more details of this project will be shared. To give it a name for now, we are calling it "Polkadot Facade".

**The aim of issue is to learn about the instances where you had to interact with Polkadot Network** (as defined above), **and you found it difficult**. This interaction can be in any form, but to help give you a mental model, I can categorize it as such: 

1. 🤓 read: You had/wish to read something from the chain (most likely a pallet's storage / runtime-api), and you found it difficult. 
2. ✍️ write: You had/wish to compose a transaction to do something, and you found it difficult.

A few notes: 

1. I used the "*had/wish*" intentionally: I would like to hear both about scenarios that you had to do something and they were hard, and those that you couldn't even figure out how to do becaues it was too hard. 
2. You can focus both on single-network interactions, and multi-network (involving XCM) interactions. That being said, we will likely first consider single-network cases.
3. When it comes to reading, don't limit yourself to what can be read from the state of a certain block, historical queries also count. 

Please feel free to reach out to me on Matrix (`@kianenigma:parity.io`) if need be.

**Comment by Tbaut** [comment]
For Delegit in particular here is what's been a pain from the top of my head:
1. Figuring out all the voting, conviction, and locks. Delegit was created particularly because barely any other app out there could figure it out correctly. What was particularly painful was to calculate the locks. I had to fetch the referenda that have been voted on, see what we voted, see what was the outcome, then see if we're locked, and if we are, calculate the unlocking block.

1. The general way the votes and delegations are stored (the returned value or `convictionVoting.voting_for`) is a mess to make sense of

1. The conviction being encoded in a weird way (on 1 byte) made it difficult to understand, but this you know already, cf https://github.com/polkadot-api/polkadot-api/issues/666

1. the weight of certain calls are wrong, make a batch of it and we're summing up the wrong calculation here's an example of `convictionVoting.remove_vote` and `convictionVoting.delegate`
Here's an example it's off by 5x https://polkadot.subscan.io/extrinsic/22738944-3
![image](https://github.com/user-attachments/assets/4f545b0b-7db0-42e7-b95b-bac6e3dc8c58)
This leads to nodes actually rejecting calls for instance bc users have not enough funds, or much worse, I've received `exhausted ressources` error for some calls on Polkadot, although it's pretty certain that these calls wouldn't have filled the blocks.

1. something that is general to all the Dapp I built: there's no source of truth for the decimal, the token name and the network name. This is also something I had pinged you about. These info are in the chain spec for now, which is a trusted place. it's be much better to have this on chain. cf https://github.com/polkadot-api/polkadot-api/issues/767#issue-2564740707

1. another thing that is maybe a long shot. I see the `Extrinsic Success` event on transacations that actually ended up failing. E.g any transaction with a `call` argument such as `proxy.proxy`, `multisig.as_multi` or `utility.batch`. Just do a something as dumb as proxy.proxy(send 1M$) and if you're effectively the proxy, it'll return an extrinsic success, but the proxy call will fail. As a Dapp dev, you have to know about all the possible ways your extrinsic may fail, in that case check for the `Utility.BatchInterrupted` event. This is a huge pain which led to very ugly code form pjs. This is now a discussion in the papi repo.. but ideally it'd be solved at a lower level. cf https://github.com/polkadot-api/polkadot-api/discussions/700

**Comment by Tbaut** [comment]
closing as nothing actionable for us.
